# Generated by Django 3.2.5 on 2022-04-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FileField(upload_to='audio/')),
            ],
            options={
                'db_table': 'Audio_store',
            },
        ),
    ]
